"""The published OpenAPI contract of the HTTP surface.

Renders the OpenAPI document for the exact application
:func:`~reactor_runtime.http.server.build_app` assembles — every route group
and the WebRTC transport — without booting a server or loading a model. The
rendered document is committed at ``api/openapi.json`` as the runtime's HTTP
contract: regenerated by ``mise run http-spec``, kept fresh by a pre-commit hook
and a unit test, and diffed by the contract gate to classify a change as
breaking or additive.
"""

from __future__ import annotations

import json
from typing import Any

from reactor_runtime.core import RuntimeConfig
from reactor_runtime.http.server import build_app
from reactor_runtime.metrics import RuntimeMetrics
from reactor_runtime.runner import Runner
from reactor_runtime.transport.webrtc.config import WebRtcConfig
from reactor_runtime.transport.webrtc.router import WebRtcRouter

# Building the application needs a metrics holder, and the holder needs an
# identity. The document describes routes and models only, so this value reaches
# nothing that is rendered. A real version here would send a reader looking for a
# dependency the document does not have.
_SPEC_VERSION = "0.0.0"


def _unbootable_peer_factory(*args: Any, **kwargs: Any) -> Any:
    """Refuse to build a peer — the spec renderer never negotiates a connection."""
    raise NotImplementedError("the OpenAPI spec renderer serves no connections")


def render_openapi() -> dict[str, Any]:
    """Render the OpenAPI document for the runtime's full HTTP surface.

    Assembles the application exactly as the served process does — the fixed
    route groups plus the WebRTC transport router — against a runner that has
    not started and a peer factory that cannot build. Route registration is
    model-independent, so the document describes the surface every runtime
    process serves regardless of the model it hosts.

    Returns:
        The OpenAPI document as a dictionary.
    """
    model_ref = "spec:UnusedSpecModel"
    metrics = RuntimeMetrics(version=_SPEC_VERSION, model=model_ref)
    runner = Runner(RuntimeConfig(model_ref=model_ref), metrics)
    transport = WebRtcRouter(WebRtcConfig(), _unbootable_peer_factory, metrics)
    return build_app(runner, [transport], runner.health, metrics).openapi()


def render_spec_json() -> str:
    """Render the OpenAPI document as canonical JSON.

    Keys are sorted and indentation fixed so the output is byte-stable across
    runs and Python versions — the committed spec diffs cleanly and the
    freshness check can compare exact bytes.

    Returns:
        The canonical JSON document, ending in a newline.
    """
    return json.dumps(render_openapi(), indent=2, sort_keys=True) + "\n"
