# Copyright (c) 2026 Reactor Technologies, Inc. All rights reserved.
$schema: reactor/v1
apiVersion: v1beta
kind: VideoModel

model:
  name: multi-gpu-video
  version: v0.0.1
  description: Experimental single-session sharded video rendering.
  resources:
    gpu:
      type: NVIDIA_A100
      count: 2

runtime:
  import: model:MultiGpuVideo
